[package]
name = "uavcan-llr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc-any = "2.3"
vhrdcan = { version = "0.1.0", optional = true }
